resources:
  schemas:
    # system1:
    #   catalog_name: bar_bu1_mig
    #   name: ${var.name_prefix}system1
    #   comment: system1
    system2:
      catalog_name: bar_bu2_mig
      name: ${var.name_prefix}system2
      comment: system2
